import { useState } from 'react';
import { ApiFailure, api } from './api';

/**
 * The persistent copilot.
 *
 * It is context-aware: whatever property, room, rate plan and dates are on
 * screen travel with the utterance, so "put a 3-night minimum here" resolves
 * without the operator repeating themselves.
 *
 * The important part is what it does NOT do. It never applies a change. It
 * shows the diff the simulation computed — counts first — and waits. The
 * confirmation sentence is generated by the platform from the real numbers,
 * not written by a model.
 */
export interface CopilotContext {
  propertyId?: string | null;
  roomTypeCode?: string | null;
  ratePlanCode?: string | null;
  selectedDates?: string[] | null;
  market?: string | null;
}

interface Turn {
  role: 'user' | 'agent';
  text: string;
  action?: any;
  data?: any;
}

const SUGGESTIONS = [
  '¿Por qué no estoy vendiendo?',
  'Crea una promoción early booking 30 días, 10% para septiembre, solo México',
  'Sube mis tarifas 8% para navidad',
  '¿Cuál es mi disponibilidad del 20 al 30 de septiembre?',
];

export function Copilot({
  context,
  onChanged,
}: {
  context: CopilotContext;
  onChanged?: () => void;
}) {
  const [open, setOpen] = useState(false);
  const [turns, setTurns] = useState<Turn[]>([]);
  const [input, setInput] = useState('');
  const [busy, setBusy] = useState(false);
  const [sessionId, setSessionId] = useState<string | null>(null);

  async function send(utterance: string) {
    if (!utterance.trim() || busy) return;
    setTurns((t) => [...t, { role: 'user', text: utterance }]);
    setInput('');
    setBusy(true);
    try {
      const res = await api.ask({ utterance, channel: 'CHAT', sessionId, context });
      setSessionId(res.action?.sessionId ?? sessionId);
      setTurns((t) => [...t, { role: 'agent', text: res.speech, action: res.action, data: res.data }]);
      if (res.action?.status === 'EXECUTED') onChanged?.();
    } catch (err) {
      const e = err instanceof ApiFailure ? err.error : { message: String(err), code: 'INTERNAL' };
      setTurns((t) => [
        ...t,
        { role: 'agent', text: `${e.message}${e.remediation ? ` — ${e.remediation}` : ''}` },
      ]);
    } finally {
      setBusy(false);
    }
  }

  async function confirm(actionId: string) {
    setBusy(true);
    try {
      const res = await api.confirm(actionId);
      setTurns((t) => [...t, { role: 'agent', text: res.speech, action: res.action }]);
      onChanged?.();
    } catch (err) {
      const e = err instanceof ApiFailure ? err.error : { message: String(err), code: 'INTERNAL' };
      setTurns((t) => [
        ...t,
        {
          role: 'agent',
          text:
            e.code === 'STEP_UP_REQUIRED'
              ? `${e.message}. ${e.remediation ?? ''}`
              : `Could not execute: ${e.message}`,
        },
      ]);
    } finally {
      setBusy(false);
    }
  }

  async function reject(actionId: string) {
    await api.reject(actionId, 'rejected from copilot');
    setTurns((t) => [...t, { role: 'agent', text: 'Discarded. Nothing was changed.' }]);
  }

  if (!open) {
    return (
      <button className="copilot-toggle" onClick={() => setOpen(true)}>
        <span className="spark">✦</span> Ask Wetriip
      </button>
    );
  }

  return (
    <div className="copilot">
      <div className="copilot-head">
        <div className="row">
          <span style={{ color: 'var(--color-brand)' }}>✦</span>
          <strong style={{ fontWeight: 500 }}>Ask Wetriip</strong>
          {context.propertyId && <span className="badge brand">in context</span>}
        </div>
        <button
          className="btn-sm"
          style={{ background: 'transparent', border: 'none', color: '#94a3b8' }}
          onClick={() => setOpen(false)}
        >
          ✕
        </button>
      </div>

      <div className="copilot-body">
        {turns.length === 0 && (
          <>
            <p className="muted" style={{ marginBottom: 12 }}>
              I can explain, recommend and prepare changes. I never apply anything without your
              confirmation.
            </p>
            {SUGGESTIONS.map((s) => (
              <button
                key={s}
                className="btn-sm"
                style={{ display: 'block', width: '100%', textAlign: 'left', marginBottom: 6 }}
                onClick={() => send(s)}
              >
                {s}
              </button>
            ))}
          </>
        )}

        {turns.map((turn, i) => (
          <div className="msg" key={i}>
            {turn.role === 'user' ? (
              <div className="msg-user">{turn.text}</div>
            ) : (
              <div className="msg-agent">
                <div>{turn.text}</div>
                {turn.action && <ActionDetail action={turn.action} onConfirm={confirm} onReject={reject} busy={busy} />}
              </div>
            )}
          </div>
        ))}
        {busy && <div className="caption">Working…</div>}
      </div>

      <div className="copilot-foot">
        <input
          value={input}
          placeholder="What do you want to change?"
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && send(input)}
        />
        <button className="btn-dark" onClick={() => send(input)} disabled={busy}>
          Send
        </button>
      </div>
    </div>
  );
}

function ActionDetail({
  action,
  onConfirm,
  onReject,
  busy,
}: {
  action: any;
  onConfirm: (id: string) => void;
  onReject: (id: string) => void;
  busy: boolean;
}) {
  const sim = action.simulation;
  const policy = action.policyDecision;
  const awaiting = action.status === 'AWAITING_CONFIRMATION';

  return (
    <div>
      <div className="row wrap" style={{ marginTop: 7 }}>
        <span className="badge">{action.agent}</span>
        <span className={`badge ${action.riskLevel === 'HIGH' ? 'danger' : action.riskLevel === 'MEDIUM' ? 'warning' : ''}`}>
          {action.riskLevel} risk
        </span>
        <span className="badge">L{action.autonomyLevel}</span>
        {/* Whether a model was involved at all is never hidden from the operator. */}
        <span className="badge">{action.deterministicIntent ? 'grammar' : (action.modelId ?? 'model')}</span>
      </div>

      {sim && sim.blastRadius && (
        <div className="diff">
          <div className="diff-row">
            <span className="muted">ARI cells</span>
            <strong>{sim.blastRadius.ariCells}</strong>
          </div>
          <div className="diff-row">
            <span className="muted">Stay dates</span>
            <strong>{sim.blastRadius.stayDates}</strong>
          </div>
          <div className="diff-row">
            <span className="muted">Rate plans</span>
            <strong>{sim.blastRadius.ratePlans}</strong>
          </div>
          {sim.projections?.avgBefore != null && (
            <div className="diff-row">
              <span className="muted">Average</span>
              <strong>
                {Math.round(sim.projections.avgBefore).toLocaleString()} →{' '}
                {Math.round(sim.projections.avgAfter ?? 0).toLocaleString()}{' '}
                {sim.projections.currency}
                {sim.projections.adrDeltaPct != null && ` (${sim.projections.adrDeltaPct > 0 ? '+' : ''}${sim.projections.adrDeltaPct}%)`}
              </strong>
            </div>
          )}
          {sim.warnings?.map((w: string) => (
            <div key={w} style={{ color: 'var(--color-warning)', marginTop: 5 }}>
              ⚠ {w}
            </div>
          ))}
          {sim.blockers?.map((b: string) => (
            <div key={b} style={{ color: 'var(--color-danger)', marginTop: 5 }}>
              ✕ {b}
            </div>
          ))}
        </div>
      )}

      {policy && !policy.allowed && (
        <div className="diff" style={{ borderColor: '#fecaca', background: '#fef2f2' }}>
          {policy.checks
            .filter((c: any) => !c.passed)
            .map((c: any) => (
              <div className="diff-row" key={c.code}>
                <span>{c.label}</span>
                <strong>
                  {c.actual} / limit {c.limit}
                </strong>
              </div>
            ))}
        </div>
      )}

      {awaiting && (
        <div className="row" style={{ marginTop: 9 }}>
          <button className="btn-primary btn-sm" onClick={() => onConfirm(action.id)} disabled={busy}>
            Confirm
          </button>
          <button className="btn-sm" onClick={() => onReject(action.id)} disabled={busy}>
            Discard
          </button>
          {action.requiresStepUp && <span className="badge warning">step-up required</span>}
        </div>
      )}
    </div>
  );
}
